# Generated by Django 4.2.7 on 2025-05-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_screen_seat_theater_showtime_screen_theater_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('REG', 'Regular'), ('PREM', 'Executive'), ('VIP', 'Premium')], default='REG', max_length=4),
        ),
    ]
