# Generated by Django 4.2.7 on 2025-05-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_seat_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('REG', 'Normal'), ('PREM', 'Executive'), ('VIP', 'Premium')], default='REG', max_length=4),
        ),
    ]
